=== martonmengyan/BPWTW0_XMLGyak/XMLTaskBPWTW0/XSDBPWTW0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="adatbazis">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="Publisher" type="publisherType" maxOccurs="unbounded"/>
			<xs:element name="Forgalmazó" type="forgalmazóType" maxOccurs="unbounded"/>
			<xs:element name="Vásárló" type="vásárlóType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Játék" type="játékType" maxOccurs="unbounded"/>
			<xs:element name="Weboldal" type="weboldalType" maxOccurs="unbounded"/>
			<xs:element name="Indok" type="indokType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:key name="vásárlóKulcs">
		<xs:selector xpath="Vásárló"/>
		<xs:field xpath="@Telefonszám"/>
	</xs:key>
	<xs:key name="játékKulcs">
		<xs:selector xpath="Játék"/>
		<xs:field xpath="@Kód"/>
	</xs:key>
	<xs:key name="forgalmazóKulcs">
		<xs:selector xpath="Forgalmazó"/>
		<xs:field xpath="@Kód"/>
	</xs:key>
	<xs:key name="weboldalKulcs">
		<xs:selector xpath="Weboldal"/>
		<xs:field xpath="@Link"/>
	</xs:key>
	<xs:keyref name="Forgalmazó-Weboldal" refer="weboldalKulcs">
		<xs:selector xpath="Forgalmazó/weboldalLink"/>
		<xs:field xpath="."/>
	</xs:keyref>
	<xs:keyref name="Vásárló-Weboldal" refer="weboldalKulcs">
		<xs:selector xpath="Vásárló/weboldalLink"/>
		<xs:field xpath="."/>
	</xs:keyref>	
	<xs:keyref name="Vásárló-Indok" refer="vásárlóKulcs">
		<xs:selector xpath="Indok/vásárlóTelefonszám"/>
		<xs:field xpath="."/>
	</xs:keyref>
	<xs:keyref name="Játék-Indok" refer="játékKulcs">
		<xs:selector xpath="Indok/játékKód"/>
		<xs:field xpath="."/>
	</xs:keyref>
	<xs:keyref name="Publisher-Forgalmazó" refer="forgalmazóKulcs">
		<xs:selector xpath="Publisher/forgalmazóKód"/>
		<xs:field xpath="."/>
	</xs:keyref>
</xs:element>

<xs:complexType name="publisherType">
	<xs:sequence>
		<xs:element name="Név" type="xs:string"/>
		<xs:element name="Ügyintéző" type="xs:string"/>
		<xs:element name="Cím" type="címType"/>
		<xs:element name="forgalmazóKód" type="xs:int"/>
	</xs:sequence>
</xs:complexType>
<xs:complexType name="forgalmazóType">
	<xs:sequence>
		<xs:element name="Alkalmazott" type="alkalmazottType" maxOccurs="unbounded"/>
		<xs:element name="Cím" type="címType"/>
		<xs:element name="weboldalLink" type="xs:string"/>
	</xs:sequence>
	<xs:attribute name="Kód" type="xs:positiveInteger"/>
</xs:complexType>
<xs:complexType name="vásárlóType">
	<xs:sequence>
		<xs:element name="Név" type="xs:string"/>
		<xs:element name="Fizetés_módja" type="fizetésType" default="Mastercard"/>
		<xs:element name="Születési_év" type="xs:int"/>
		<xs:element name="Cím" type="címType"/>
		<xs:element name="weboldalLink" type="xs:string"/>
	</xs:sequence>
	<xs:attribute name="Telefonszám" type="xs:positiveInteger"/>
</xs:complexType>
<xs:complexType name="játékType">
	<xs:sequence>
		<xs:element name="Ár" type="xs:int"/>
		<xs:element name="Kategória" type="kategóriaType" default="Action Games"/>
		<xs:element name="Platform" type="platformType" default="PC"/>
	</xs:sequence>
	<xs:attribute name="Kód" type="xs:positiveInteger"/>
</xs:complexType>
<xs:complexType name="weboldalType">
	<xs:sequence>
		<xs:element name="Karbantartó" type="karbantartóType"/>
	</xs:sequence>
	<xs:attribute name="Link" type="xs:string"/>
</xs:complexType>
<xs:complexType name="alkalmazottType">
	<xs:sequence>
		<xs:element name="Név" type="xs:string"/>
		<xs:element name="Email" type="emailType"/>
	</xs:sequence>
</xs:complexType>
<xs:complexType name="karbantartóType">
	<xs:sequence>
		<xs:element name="Név" type="xs:string"/>
		<xs:element name="Email" type="emailType"/>
	</xs:sequence>
</xs:complexType>
<xs:complexType name="címType">
	<xs:sequence>
		<xs:element name="Irányítószám" type="xs:int"/>
		<xs:element name="Város" type="xs:string"/>
		<xs:element name="Utca" type="xs:string"/>
		<xs:element name="Házszám" type="xs:int"/>
	</xs:sequence>
</xs:complexType>
<xs:simpleType name="kategóriaType">
	<xs:restriction base="xs:string">
		<xs:enumeration value="Action Games"/>
		<xs:enumeration value="Action-Adventure Games"/>
		<xs:enumeration value="Adventure Games"/>
		<xs:enumeration value="Role-Playing Games"/>
		<xs:enumeration value="Simulation Games"/>
		<xs:enumeration value="Strategy Games"/>
		<xs:enumeration value="Sports Games"/>
	</xs:restriction>
</xs:simpleType>
<xs:simpleType name="fizetésType">
	<xs:restriction base="xs:string">
		<xs:enumeration value="PayPal"/>
		<xs:enumeration value="Mastercard"/>
	</xs:restriction>
</xs:simpleType>
<xs:simpleType name="platformType">
	<xs:restriction base="xs:string">
		<xs:enumeration value="PC"/>
		<xs:enumeration value="PS4"/>
		<xs:enumeration value="PS3"/>
		<xs:enumeration value="XBOX"/>
	</xs:restriction>
</xs:simpleType>
<xs:complexType name="indokType">
	<xs:sequence>
		<xs:element name="Szabadidő" type="xs:boolean"/>
		<xs:element name="Karantén" type="xs:boolean"/>
		<xs:element name="Lazítás" type="xs:boolean"/>
		<xs:element name="vásárlóTelefonszám" type="xs:positiveInteger"/>
		<xs:element name="játékKód" type="xs:int"/>
	</xs:sequence>
</xs:complexType>
<xs:simpleType name="emailType"> 
	<xs:restriction base="xs:string"> 
		<xs:pattern value="[^@]+@[^\.]+\..+|"/> 
	</xs:restriction> 
</xs:simpleType> 
</xs:schema>

=== martonmengyan/BPWTW0_XMLGyak/XMLTaskBPWTW0/XMLBPWTW0.xml
<?xml version="1.0" encoding="UTF-8"?>

<adatbazis 	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:noNamespaceSchemaLocation="XSDBPWTW0.xsd">

<!-- Publisherek -->

	<Publisher>
		<Név>GamesProdigy</Név>
		<Ügyintéző>Hazárdy Enikő</Ügyintéző>
		<Cím>
			<Irányítószám>3522</Irányítószám>
			<Város>Miskolc</Város>
			<Utca>Kehely</Utca>
			<Házszám>4</Házszám>
		</Cím>
		<forgalmazóKód>1</forgalmazóKód>
	</Publisher>
	
	<Publisher>
		<Név>DuckGames</Név>
		<Ügyintéző>Nagy Dániel</Ügyintéző>
		<Cím>
			<Irányítószám>3542</Irányítószám>
			<Város>Miskolc</Város>
			<Utca>Benedek</Utca>
			<Házszám>22</Házszám>
		</Cím>
		<forgalmazóKód>2</forgalmazóKód>
	</Publisher>

<!-- Forgalmazók -->

	<Forgalmazó Kód="1">
		<Alkalmazott>
			<Név>Kiss Pista</Név>
			<Email>pistakiss@gmail.com</Email>
		</Alkalmazott>
		<Alkalmazott>
			<Név>Nagy Anett</Név>
			<Email>anettnagy88@freemail.hu</Email>
		</Alkalmazott>
		<Alkalmazott>
			<Név>Orosz Márton</Név>
			<Email>martonorosz00@gmail.hu</Email>
		</Alkalmazott>
		<Cím>
			<Irányítószám>3537</Irányítószám>
			<Város>Miskolc</Város>
			<Utca>Csésze</Utca>
			<Házszám>14</Házszám>
		</Cím>
		<weboldalLink>www.sfeam.com</weboldalLink>
	</Forgalmazó>
	
	<Forgalmazó Kód="2">
		<Alkalmazott>
			<Név>Fekete Nándor</Név>
			<Email>nandorfekete@citromail.hu</Email>
		</Alkalmazott>
		<Alkalmazott>
			<Név>Nagy Lajos</Név>
			<Email>lajosnagy@gmail.hu</Email>
		</Alkalmazott>
		<Alkalmazott>
			<Név>Molnár Péter</Név>
			<Email>petermolnar@freemail.hu</Email>
		</Alkalmazott>
		<Cím>
			<Irányítószám>3508</Irányítószám>
			<Város>Miskolc</Város>
			<Utca>Danta</Utca>
			<Házszám>7</Házszám>
		</Cím>
		<weboldalLink>www.urisoft.com</weboldalLink>
	</Forgalmazó>

<!-- Vásárlók -->

	<Vásárló Telefonszám="06605441284">
		<Név>Lengyel Anna</Név>
		<Fizetés_módja>PayPal</Fizetés_módja>
		<Születési_év>2001</Születési_év>
		<Cím>
			<Irányítószám>3543</Irányítószám>
			<Város>Miskolc</Város>
			<Utca>Cipő</Utca>
			<Házszám>27</Házszám>
		</Cím>
		<weboldalLink>www.sfeam.com</weboldalLink>
	</Vásárló>
	
	<Vásárló Telefonszám="06605851274">
		<Név>Kovács Vanessza</Név>
		<Fizetés_módja></Fizetés_módja>
		<Születési_év>1997</Születési_év>
		<Cím>
			<Irányítószám>3612</Irányítószám>
			<Város>Miskolc</Város>
			<Utca>Sisak</Utca>
			<Házszám>15</Házszám>
		</Cím>
		<weboldalLink>www.sfeam.com</weboldalLink>
	</Vásárló>
	
	<Vásárló Telefonszám="06605556224">
		<Név>Varga Márk</Név>
		<Fizetés_módja>Mastercard</Fizetés_módja>
		<Születési_év>2007</Születési_év>
		<Cím>
			<Irányítószám>3508</Irányítószám>
			<Város>Miskolc</Város>
			<Utca>Péter</Utca>
			<Házszám>9</Házszám>
		</Cím>
		<weboldalLink>www.urisoft.com</weboldalLink>
	</Vásárló>

<!-- Játékok -->

	<Játék Kód="1">
		<Ár>14999</Ár>
		<Kategória>Sports Games</Kategória>
		<Platform>PS4</Platform>
	</Játék>
	
	<Játék Kód="2">
		<Ár>7999</Ár>
		<Kategória>Role-Playing Games</Kategória>
		<Platform>XBOX</Platform>
	</Játék>
	
	<Játék Kód="3">
		<Ár>4999</Ár>
		<Kategória></Kategória>
		<Platform></Platform>
	</Játék>

<!-- Weboldalak -->

	<Weboldal Link="www.urisoft.com">
		<Karbantartó>
			<Név>Kiss Ádám</Név>
			<Email>urisoftmanagment@gmail.com</Email>
		</Karbantartó>
	</Weboldal>

	<Weboldal Link="www.sfeam.com">
		<Karbantartó>
			<Név>Kovács Gábor</Név>
			<Email>sfeammanagment@gmail.com</Email>
		</Karbantartó>
	</Weboldal>

<!-- Indok -->

	<Indok>
		<Szabadidő>false</Szabadidő>
		<Karantén>false</Karantén>
		<Lazítás>true</Lazítás>
		<vásárlóTelefonszám>06605441284</vásárlóTelefonszám>
		<játékKód>1</játékKód>
	</Indok>
	
	<Indok>
		<Szabadidő>true</Szabadidő>
		<Karantén>false</Karantén>
		<Lazítás>false</Lazítás>
		<vásárlóTelefonszám>06605851274</vásárlóTelefonszám>
		<játékKód>2</játékKód>
	</Indok>
	
	<Indok>
		<Szabadidő>false</Szabadidő>
		<Karantén>true</Karantén>
		<Lazítás>false</Lazítás>
		<vásárlóTelefonszám>06605556224</vásárlóTelefonszám>
		<játékKód>3</játékKód>
	</Indok>
</adatbazis>
