=== martonmengyan/BPWTW0_XMLGyak/BPWTW0_1006/MM_ertoxsd.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="ertoxsd">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="A">
				<xs:complexType mixed="true">
					<xs:sequence>
						<xs:element name="b1" type="xs:string"/>
						<xs:element name="c1" type="xs:string"/>
					</xs:sequence>
					<xs:attribute name="a1" type="xs:int" use="required"/>
				</xs:complexType>
			</xs:element>
			
			<xs:element name="b1" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="x1" type="xs:string"/>
						<xs:element name="y1" type="xs:string"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			
			<xs:element name="c1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="d1" type="xs:string"/>
						<xs:element name="e1" type="xs:string"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			
			<xs:element name="B">
				<xs:complexType mixed="true">
					<xs:sequence>
						<xs:element name="b2" type="xs:string"/>
					</xs:sequence>
					<xs:attribute name="a2" type="xs:int" use="required"/>
				</xs:complexType>
			</xs:element>
			
			<xs:element name="b2">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="x2" type="xs:string"/>
						<xs:element name="y2" type="xs:string"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			
			<xs:element name="C">
				<xs:complexType mixed="true">
					<xs:sequence>
						<xs:element name="b3" type="xs:string"/>
					</xs:sequence>
					<xs:attribute name="a3" type="xs:int" use="required"/>
				</xs:complexType>
			</xs:element>
			
		</xs:sequence>
	</xs:complexType>
</xs:element>



</xs:schema>

=== martonmengyan/BPWTW0_XMLGyak/BPWTW0_1006/MM_ertoxsd.xml
<?xml version="1.0" encoding="utf-8"?>

<ertoxsd xmlns:xsi="http://www.w3.org/2001/XMLSchema"
			xsi:noNamespaceSchemaLocation="MM_ertoxsd.xsd">
			
	<A a1="1">
		<b1>
		<x1>x1</x1>
		<y1>y1</y1>
		</b1>
		<b1>
		<x1>x12</x1>
		<y1>y12</y1>
		</b1>
		<c1>c1</c1>
	</A>
	<B a2="2">
		<b2>
		<x2>x2</x2>
		<y2>y2</y2>
		</b2>
	</B>	
	<C a3="3">
		<b3>b3</b3>
	</C>		
			
</ertoxsd>
