=== martonmengyan/BPWTW0_XMLGyak/BPWTW0_0928/MM_konyv.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT konyvek (konyv*)>

<!ELEMENT konyv (cim, kiadasi_ev, kiado, szerzo+)>
<!ATTLIST konyv id CDATA #REQUIRED>

<!ELEMENT kiadasi_ev (#PCDATA)>
<!ELEMENT cim (#PCDATA)>
<!ELEMENT kiado (#PCDATA)>
<!ELEMENT szerzo (#PCDATA)>

=== martonmengyan/BPWTW0_XMLGyak/BPWTW0_0928/MM_konyv.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE konyvek SYSTEM "MM_konyv.dtd">

<konyvek>
	<konyv id="1">
	<cim>Programozás</cim>
	<kiadasi_ev>ASD</kiadasi_ev>
	<kiado>Konyv Kiado</kiado>
	<szerzo>Kis István</szerzo>
	<szerzo>Molnár Károly</szerzo>
	</konyv>
	<konyv id="2">
	<cim>O.O.P.</cim>
	<kiadasi_ev>ASD</kiadasi_ev>
	<kiado>Konyv Kiado</kiado>
	<szerzo>Nagy Antal</szerzo>
	</konyv>
	<konyv id="3">
	<cim>XML</cim>
	<kiadasi_ev>ASD</kiadasi_ev>
	<kiado>Konyv Kiado</kiado>
	<szerzo>Nyáradi Máté</szerzo>
	</konyv>
</konyvek>
