=== martonmengyan/BPWTW0_XMLGyak/BPWTW0_1013/MM_nevjegykartya.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="nevjegykartyak">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="nevjegykartya" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="nevjegykartya">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="nev" type="xs:string"/>
				<xs:element name="ceg" type="cegTipus"/>
				<xs:element name="beosztas" type="beosztasTipus"/>
				<xs:element name="telefonszam" type="xs:positiveInteger"/>
				<xs:element name="email" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="cegTipus">
		<xs:sequence>
			<xs:element name="nev" type="xs:string" />
			<xs:element name="cim" type="cimTipus" />
			<xs:element name="telefonszam" type="xs:string" />
			<xs:element name="web" type="xs:string" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="cimTipus">
		<xs:sequence>
			<xs:element name="iranyitoszam" type="xs:string" />
			<xs:element name="varos" type="xs:string" />
			<xs:element name="utca" type="xs:string" />
			<xs:element name="hazszam" type="xs:positiveInteger" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:simpleType name="beosztasTipus">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Fonok"/>
			<xs:enumeration value="Beosztott"/>
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== martonmengyan/BPWTW0_XMLGyak/BPWTW0_1013/MM_nevjegykartya.xml
<?xml version="1.0" encoding="UTF-8"?>

<nevjegykartyak		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
					xsi:noNamespaceSchemaLocation="MM_nevjegykartya.xsd">
	<nevjegykartya>
		<nev>Kiss Lajos</nev>
		<ceg>
			<nev>Auto Kft.</nev>
			<cim>
				<iranyitoszam>3312</iranyitoszam>
				<varos>Miskolc</varos>
				<utca>Erdo utca</utca>
				<hazszam>23</hazszam>
			</cim>
			<telefonszam>06705657889</telefonszam>
			<weblap>kisslajosauto.hu</weblap>
		</ceg>
		<beosztas>Fonok</beosztas>
		<telefonszam>06705657889</telefonszam>
		<email>kisslajos@gmail.com</email>
	</nevjegykartya>
	
	<nevjegykartya>
		<nev>Nagy Mate</nev>
		<ceg>
			<nev>Auto Kft.</nev>
			<cim>
				<iranyitoszam>3312</iranyitoszam>
				<varos>Miskolc</varos>
				<utca>Erdo utca</utca>
				<hazszam>23</hazszam>
			</cim>
			<telefonszam>06705657889</telefonszam>
			<weblap>kisslajosauto.hu</weblap>
		</ceg>
		<beosztas>Beosztott</beosztas>
		<telefonszam>06705657320</telefonszam>
		<email>nagymate@gmail.com</email>
	</nevjegykartya>
</nevjegykartyak>
