=== martonmengyan/BPWTW0_XMLGyak/BPWTW0_1020/src/macskakBPWTW0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema	xmlns:xs="http://www.w3.org/2001/XMLSchema">
			
	<xs:element name="macskak">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="macska" minOccurs="3" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>	
	
	<xs:element name="macska">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="nev" type="xs:string"/>
				<xs:element name="kor" type="xs:int"/>
				<xs:element name="fajta" type="xs:string"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:positiveInteger"/>
		</xs:complexType>
	</xs:element>		
			
</xs:schema>

=== martonmengyan/BPWTW0_XMLGyak/BPWTW0_1020/bin/macskakBPWTW0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE udvar SYSTEM "macskakBPWTW0.dtd">  -->
<macskak	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:noNamespaceSchemaLocation="macskakBPWTW0.xsd">

	<macska id="1">
		<nev></nev>
		<kor></kor>
		<fajta></fajta>
	</macska>
	<macska id="2">
		<nev></nev>
		<kor></kor>
		<fajta></fajta>
	</macska>
	<macska id="3">
		<nev></nev>
		<kor></kor>
		<fajta></fajta>
	</macska>

</macskak>

=== martonmengyan/BPWTW0_XMLGyak/SaxBPWTW0/bin/macskakBPWTW0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE udvar SYSTEM "macskakBPWTW0.dtd">  -->
<macskak	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:noNamespaceSchemaLocation="macskakBPWTW0.xsd">

	<macska id="1">
		<nev>nev1</nev>
		<kor>3</kor>
		<fajta>fajta1</fajta>
	</macska>
	<macska id="2">
		<nev>nev2</nev>
		<kor>4</kor>
		<fajta>fajta2</fajta>
	</macska>
	<macska id="3">
		<nev>nev3</nev>
		<kor>3</kor>
		<fajta>fajta3</fajta>
	</macska>

</macskak>
